# apxo.config.yaml
# Default configuration for the Allotment Procurement & Demand Simulation (Agent v1)

# Phase / timing controls
ticks_total: 12            # 12 monthly ticks ~ 12 minutes
seconds_per_tick: 60
rng_seed: 42

airline:
  C_total: 180             # Total seats on the flight
  P_airline_start: 120
  P_min: 80
  P_max: 400
  gamma: 0.15              # Repricing speed (forecast feedback)
  kappa: 50                # Smoothing factor

market:
  # Booking curve: low early demand, steep ramp toward departure
  D_base: [6, 7, 8, 10, 12, 16, 20, 26, 34, 44, 58, 79]
  alpha: 1.1               # Price sensitivity
  beta: 6.0                # Price loyalty in the logit model
  P_ref: 150               # Reference price for price response

hotel:
  capacity_per_team: 60
  penalty_empty_bed: 50

teams:
  - id: "A"
    P_start: 199
    P_floor: 99
    P_ceil: 499
  - id: "B"
    P_start: 189
    P_floor: 99
    P_ceil: 499
  - id: "C"
    P_start: 209
    P_floor: 99
    P_ceil: 499

rules:
  need_price_above_cost: true
  push_cost_per_level: [0, 200, 600]   # Budget deduction (if the budget model is enabled)
  tool_cooldown_ticks: 3
  price_jump_threshold: 0.10           # "large" price change >10% per tick (drives cooldown/warnings)
  anti_collusion_band_pct: 0.01        # +/-1% band across 3 ticks produces a small attention penalty
